### PR TITLE
Fix incorrect last modified date in json+ld

### LINKED ISSUE #558: Last Modified date is wrong in the json+ld
## Describe the bug
The last modified date in the json+ld output by the parsely plugin is wrong. It always outputs the created date due to the if statement.

On: 
https://github.com/Parsely/wp-parsely/blob/7c372ca9e26bb3c0af14d2b81af355644ed2cea3/src/class-parsely.php#L452
https://github.com/Parsely/wp-parsely/blob/7c372ca9e26bb3c0af14d2b81af355644ed2cea3/src/class-parsely.php#L453

The function code is using: get_the_modified_date( 'U', true )

The documentation: https://developer.wordpress.org/reference/functions/get_the_modified_date/ says that the second argument should be post object or post ID. Using true returns a bad value. Changing true to $post should fix the issue although will probably not be in GMT time.

Given the code, I'm assuming you probably meant to use: get_post_modified_time  
https://developer.wordpress.org/reference/functions/get_post_modified_time/

In which case swapping out the functions would work fine with the original code (although still probably should explicitly pass in the $post object for the third argument).

## To Reproduce
Go to any page with parsely plugin enabled and the view the json+ld data.

## Expected behaviour
Returns the last modified date of the post.

### LINKED ISSUE #562: Reports of fatal error coming from plugin
Multiple Parse.ly users have reported the following error coming from the plugin:

```
Fatal error: Uncaught Error: gmdate() expects parameter 2 to be int, bool given
in /var/www/wp-content/plugins/wp-parsely/src/class-parsely.php on line 450
```

One shared data from its log files. I've obscured the customer name:

```
2021-12-27 14:08:23.821171 [NOTICE] [9118] [T0] [204.237.142.109:33881#APVH_xxxxxxx:443 (http://204.237.142.109:33881/#APVH_xxxxxxx:443) ] [STDERR] PHP Fatal error: Uncaught TypeError: gmdate() expects parameter 2 to be int, bool given in /var/www/vhosts/xxxxxxx/httpdocs/wp-content/plugins/wp-parsely/src/class-parsely.php:450

Stack trace:

#0 /var/www/vhosts/xxxxxxx/httpdocs/wp-content/plugins/wp-parsely/src/class-parsely.php(450): gmdate()

#1 /var/www/vhosts/xxxxxxx/httpdocs/wp-content/plugins/wp-parsely/src/class-parsely.php(189): Parsely\Parsely->construct_parsely_metadata()

#2 /var/www/vhosts/xxxxxxx/httpdocs/wp-includes/class-wp-hook.php(292): Parsely\Parsely->insert_page_header_metadata()

#3 /var/www/vhosts/xxxxxxx/httpdocs/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()

#4 /var/www/vhosts/xxxxxxx/httpdocs/wp-includes/plugin.php(484): WP_Hook->do_action()

#5 /var/www/vhosts/xxxxxxx/httpdocs/wp-includes/general-template.php(3009): do_action()

#6 /var/www/vhosts/xxxxxxx/httpdocs/wp-content/themes/tpd-theme/header.php(18): wp_head()

#7 /var/www/vhosts/xxxxxxx/httpdocs/wp-includes/template.php(730): require_once('/var/www in /var/www/vhosts/xxxxxxx/httpdocs/wp-content/plugins/wp-parsely/src/class-parsely.php on line 450

When we de-activated the plugin, the site performance returned to normal levels.
```

### PR DESCRIPTION
**Pull request by acicovic**
## Description
This PR attempts to resolve an issue where the last modified date in the json+ld output could be wrong.  Additionally, this fixes potential fatal errors caused by passing `false` into the second param of the `gmdate` function now that we're enforcing strict types for function parameters.

Fixes #558
Fixes #562

## Motivation and Context
More details about the issue can be found in #558. This is something that should be fixed and we should aim to add a test for it.

## How Has This Been Tested?
So far only by examining browser output and by examining variables using step debugging, but will also look into writing a test for this.

### CODE REVIEW

**Comment by GaryJones** [comment]
Can we avoid calling the same function with the same args twice, and also defensively check it didn't return false before passing it to a function that requires an integer?

**Comment by acicovic** [comment]
@GaryJones I've updated this based on your feedback and took the liberty to extract it as a function. Let me know should you have any feedback.

File: src/class-parsely.php [hunk 1]
```diff
@@ -492,6 +487,31 @@ public function construct_parsely_metadata( array $parsely_options, WP_Post $pos
...
+	 * Sets all metadata values related to post time.
+	 *
+	 * @param array   $metadata Array containing all metadata.
+	 * @param WP_Post $post Post object from which to extract time data.
+	 * @return void
+	 */
+	private function set_metadata_post_times( array &$metadata, WP_Post $post ): void {
+		// Initializations.
+		$date_format   = 'Y-m-d\TH:i:s\Z';
+		$post_time     = get_post_time( 'U', true, $post );
```
Comment (GaryJones) [inline src/class-parsely.php]: As per https://developer.wordpress.org/reference/functions/get_post_time/ - this function can return `false`, so a guard needs adding here.

File: src/class-parsely.php [hunk 2]
```diff
@@ -492,6 +487,31 @@ public function construct_parsely_metadata( array $parsely_options, WP_Post $pos
 		return apply_filters( 'wp_parsely_metadata', $parsely_page, $post, $parsely_options );
 	}
 
+	/**
+	 * Sets all metadata values related to post time.
+	 *
+	 * @param array   $metadata Array containing all metadata.
+	 * @param WP_Post $post Post object from which to extract time data.
```
Comment (GaryJones) [inline src/class-parsely.php]:
```suggestion
	 * @param array   $metadata Array containing all metadata.
	 * @param WP_Post $post     Post object from which to extract time data.
```

**Review by GaryJones — DISMISSED** [review]

File: tests/Integration/StructuredData/SinglePostTest.php [hunk 3]
```diff
@@ -430,6 +430,191 @@ public function test_http_canonicals_for_single_post(): void {
...
+		self::assertSame( $date_created, $metadata['dateModified'] );
+
+		// Update the post and reload metadata.
+		wp_update_post( array( 'ID' => $post_id ) );
+		$post_updated     = get_post( $post_id );
+		$metadata_updated = $parsely->construct_parsely_metadata( $parsely_options, $post_updated );
+
+		// In the metadata, check that the last modified date has been updated.
+		self::assertSame( $date_created, $metadata_updated['dateCreated'] );
+		self::assertNotSame( $date_created, $metadata_updated['dateModified'] );
```
Comment (jblz) [inline tests/Integration/StructuredData/SinglePostTest.php:482]: This assertion missed that `dateModified` was not formatted to a date string -- it should check for a particular value (or at least a meaningful relationship to the `$date_created`) instead of calling `assertNotSame`.

**Review by jblz — CHANGES_REQUESTED** [review]
I've added some fixes & more specific tests.

I think we can probably pull out `test_metadata_post_modified_date` altogether as it's covered by the other tests.

I avoided juggling `wp_update_post`, etc. and just manually annotated the `WP_Post` object which I think will suffice for these tests, but I'm happy to hear why it won't if there's reason.

File: tests/Integration/StructuredData/SinglePostTest.php (hunk 3 above)
Comment (acicovic) [reply tests/Integration/StructuredData/SinglePostTest.php:482]: I have no objections about `test_metadata_post_modified_date()` being removed if reviewers think it was rendered redundant.

My opinion (and rationale behind this implementation) is that in all integration tests we should use WP functions as much as possible, since in a regular workflow the data is manipulated by WP functions, and as such we should test with the data received by them. So I don't find "modified object" tests bad, but testing with WP built-in functions is a "reality check" that should be done IMO.

This doesn't rule out modifying objects with extreme or unexpected values to see what happens. However, the premise is that WP functions are upstream and should have their own tests to verify their quality and results. If their tests are lacking, they should be added there.

So regarding the missed assertion:

- I do expect `wp_update_post()` to add a correct date (in format and value) to the database.
- As I could not hardcode a time using `wp_update_post()`, the time could (at least theoretically) change at the time of comparison. But something that could be done to improve this is compare that modified time is in a 1-2 second window from the current time. But even this could fail under certain circumstances (for example performance problems).
- Given the previous point, I decided just to test for `NotSame` and that this would be good enough.

Having said that, team feedback is more important than my own opinion, so if any adjustments must be made or the test must be removed, that's fine by me.

Comment (jblz) [reply tests/Integration/StructuredData/SinglePostTest.php:482]: > in all integration tests we should use WP functions as much as possible, since in a regular workflow the data is manipulated by WP functions, and as such we should test with the data received by them

I agree in general. If `set_metadata_post_times` (& by proxy `construct_parsely_metadata`) were operating against the "current" post or some global, I'd probably be in favor of going the extra mile to call `wp_update_post`. Since they just take a post object, I'm less pressed about it, personally.

Maybe we leave both and move the tests I added to `tests/Unit`...?  Your call.

Comment (GaryJones) [reply tests/Integration/StructuredData/SinglePostTest.php:482]: > Maybe we leave both and move the tests I added to `tests/Unit`...? 

By definition of the tests including `$this->factory->post->create();`, they can't be unit tests. You'd have to instantiate `WP_Post` directly, and I suspect that might be painful to populate without a DB entry to pull from.

File: src/class-parsely.php [hunk 4]
```diff
@@ -492,6 +487,37 @@ public function construct_parsely_metadata( array $parsely_options, WP_Post $pos
...
 
+	/**
+	 * Sets all metadata values related to post time.
+	 *
+	 * @param array   $metadata Array containing all metadata. It will be potentially mutated to add keys: dateCreated, dateModified, & datePublished.
+	 * @param WP_Post $post     Post object from which to extract time data.
+	 * @return void
+	 */
+	private function set_metadata_post_times( array &$metadata, WP_Post $post ): void {
+		$date_format = 'Y-m-d\TH:i:s\Z';
```
Comment (pauarge) [inline src/class-parsely.php]: Could we extract this to a constant within the class?

File: src/class-parsely.php [hunk 5]
```diff
@@ -492,6 +487,37 @@ public function construct_parsely_metadata( array $parsely_options, WP_Post $pos
...
+		$post_time   = get_post_time( 'U', true, $post );
+
+		if ( false === $post_time ) {
+			return;
+		}
+
+		$post_time_gmt = gmdate( $date_format, $post_time );
+
+		// Set post created and published time.
```
Comment (pauarge) [inline src/class-parsely.php]: I would get rid of this comment since it is quite straight forward what the code is doing.

File: src/class-parsely.php [hunk 6]
```diff
@@ -492,6 +487,37 @@ public function construct_parsely_metadata( array $parsely_options, WP_Post $pos
...
+		$metadata['dateCreated']   = $post_time_gmt;
+		$metadata['datePublished'] = $post_time_gmt;
+
+		// Set post modified time.
+		$metadata['dateModified'] = $post_time_gmt;
```
Comment (pauarge) [inline src/class-parsely.php]: Could we set this a inside (for instance) and `else` in the later conditional? We are setting this variable twice, when ideally we should check for the condition and then set it accordingly.

**Review by pauarge — CHANGES_REQUESTED** [review]
Thanks for working on this. I left some possible refinements in the code.

**Comment by pauarge** [comment]
Also, we should first merge @jblz 's PR into this one and then this one into `develop`.

File: src/class-parsely.php (hunk 4 above)
Comment (GaryJones) [reply src/class-parsely.php]: What benefit does that serve?

File: src/class-parsely.php (hunk 6 above)
Comment (GaryJones) [reply src/class-parsely.php]: Since it's going to be set anyway, it's better practice to avoid `else` clauses - [set it once, and overwrite it if necessary](https://phpmd.org/rules/cleancode.html#elseexpression). It reduces the [cyclomatic complexity](https://www.axelerant.com/blog/reducing-cyclomatic-complexity-and-npath-complexity-steps-for-refactoring).

Comment (pauarge) [reply src/class-parsely.php]: I see your point on cyclomatic complexity and I agree with it. My comment comes from trying to avoid doing useless overwrites, which do waste resources (granted, not many of them).

File: src/class-parsely.php (hunk 4 above)
Comment (pauarge) [reply src/class-parsely.php]: I see this is only used inside this function. Dismiss my comment.

File: src/class-parsely.php (hunk 6 above)
Comment (acicovic) [reply src/class-parsely.php]: @pauarge can you recheck the function and see if it is OK with you?
I also in general tend to avoid if/else when possible.

File: tests/Integration/StructuredData/SinglePostTest.php (hunk 3 above)
Comment (acicovic) [reply tests/Integration/StructuredData/SinglePostTest.php:482]: I'm not very clear on what needs to be done here. I suggest leaving all tests as they are (no move to unit tests) unless something needs to be removed. If we start adding lots of tests for metadata perhaps it would be good to split the file into many parts (?) - though splitting the file is not in the scope of this PR.

**Review by pauarge — APPROVED** [review]

**Comment by acicovic** [comment]
Credit: The commit https://github.com/Parsely/wp-parsely/pull/560/commits/11167e95d519acf39fbe63b50f20dc0cfa9eeb75 is based on the work in https://github.com/Parsely/wp-parsely/pull/565 by @jblz.

File: tests/Integration/StructuredData/SinglePostTest.php (hunk 3 above)
Comment (jblz) [reply tests/Integration/StructuredData/SinglePostTest.php:482]: > I suggest leaving all tests as they are

Works for me

**Review by jblz — APPROVED** [review]
