### PR TITLE
Fix some fatal errors and warnings

### LINKED ISSUE #1445: Fix admin bar warnings in Custom Post Type Archives
## Describe the bug
The admin bar produces some warnings on Custom Post Type Archives.

## To Reproduce
1. Create a CPT.
2. Visit the CPT's Archive page.
3. PHP errors should appear in the log.

## Expected behavior
No warnings should occur.

## Screenshots
image

### PR DESCRIPTION
**Pull request by acicovic**
## Description
This PR fixes all fatal errors we had in the last 15 days, as well as some warnings.

For some other warnings, I'll be keeping an eye to monitor the situation.

One of the issues that prompted this PR mentions a couple of warnings in the Recommended Widget. These have not occurred in the last 15 days and have been ignored since the widget is to be removed in the future and it has very low usage.

This PR closes #1445, #1460 and #1461.

## Motivation and context
We don't want errors!

## How has this been tested?
Existing tests pass.

### CODE REVIEW

File: src/Endpoints/class-analytics-posts-api-proxy.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ static function( stdClass $item ) use ( $date_format, $site_id ) {
 				return (object) array(
 					'author'         => $item->author,
 					'dashUrl'        => Parsely::get_dash_url( $site_id, $item->url ),
-					'date'           => wp_date( $date_format, strtotime( $item->pub_date ) ),
+					'date'           => $item->pub_date ? wp_date( $date_format, strtotime( $item->pub_date ) ) : '',
```
Comment (acicovic) [inline src/Endpoints/class-analytics-posts-api-proxy.php:58]: `$item->pub_date` could be null, resulting in fatals because the `strtotime()` function would receive a null argument.

File: src/UI/class-admin-bar.php [hunk 2]
```diff
@@ -73,7 +73,7 @@ public function admin_bar_parsely_stats_button( WP_Admin_Bar $admin_bar ): void
 		 */
 		$current_object = $GLOBALS['wp_the_query']->get_queried_object();
 
-		if ( null === $current_object || '' === $current_object->post_type ) {
+		if ( null === $current_object || null === $current_object->post_type || '' === $current_object->post_type ) {
```
Comment (acicovic) [inline src/UI/class-admin-bar.php:76]: We were continuing even if `$current_object->post_type` was null, which was generating warnings down the line.

File: src/UI/class-recommended-widget.php [hunk 3]
```diff
@@ -143,7 +143,7 @@ public function widget( $args, $widget_settings ): void /* @phpstan-ignore-line
 		// Set up the variables.
 		$api_url = $this->get_api_url(
 			$this->parsely->get_site_id(),
-			$instance['published_within'],
+			(int) $instance['published_within'], // @phpstan-ignore-line
```
Comment (acicovic) [inline src/UI/class-recommended-widget.php:146]: Quick fix for a fatal in the Recommended Widget, which is to be dropped in a future release.

File: src/Utils/utils.php [hunk 4]
```diff
@@ -123,7 +123,7 @@ function get_int_query_var( $var ): int {
 	 *
 	 * @var int
 	 */
-	return get_query_var( $var );
+	return get_query_var( $var, 0 );
```
Comment (acicovic) [inline src/Utils/utils.php:126]: The function was supposed to return an int, but the `get_query_var()` function returns an empty string by default, which would result in a fatal.

**Review by mehmoodak — APPROVED** [review]
Thanks for quickly fixing these warnings and errors.
