### PR TITLE
Make WordPress_Cache use built-in caching functions

### LINKED ISSUE #749: Fatal Error occurring on site
## Describe the bug

Parsely customer is experiencing a fatal error that prevented their site from loading. The text of this error is here:

[29-Mar-2022 14:50:50 UTC] PHP Fatal error: Uncaught TypeError: Argument 1 passed to Parsely\RemoteAPI\WordPress_Cache::__construct() must be an instance of WP_Object_Cache, instance of RedisCachePro\ObjectCaches\PhpRedisObjectCache given, called in /dom33009/wp-content/plugins/wp-parsely/wp-parsely.php on line 144 and defined in /dom33009/wp-content/plugins/wp-parsely/src/RemoteAPI/class-wordpress-cache.php:31
Stack trace:
[#0](https://wordpressvip.zendesk.com/agent/tickets/0) /dom33009/wp-content/plugins/wp-parsely/wp-parsely.php(144): Parsely\RemoteAPI\WordPress_Cache->__construct(Object(RedisCachePro\ObjectCaches\PhpRedisObjectCache))
[#1](https://wordpressvip.zendesk.com/agent/tickets/1) /wordpress-versions/5.8.4/wp-includes/class-wp-hook.php(303): Parsely\parsely_rest_api_init(Object(WP_REST_Server))
[#2](https://wordpressvip.zendesk.com/agent/tickets/2) /wordpress-versions/5.8.4/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
[#3](https://wordpressvip.zendesk.com/agent/tickets/3) /wordpress-versions/5.8.4/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
[#4](https://wordpressvip.zendesk.com/agent/tickets/4) /wordpress-versions/5.8.4/wp-includes/rest-api.php(537): do_action('rest_api_init', Object(WP_REST_Server))
[#5](https://wordpressvip.zendesk.com/agent/tickets/5) /wordpress-versions/5.8.4/wp-includes/rest-api.php(495) in /dom33009/wp-content/plugins/wp-parsely/src/RemoteAPI/class-wordpress-cache.php on line 31
[

Unfortunately this is all the context I have so far, I have asked for more. (environment, VIP or not, etc.) I will update when I know more.

### PR DESCRIPTION
**Pull request by acicovic**
## Description
In the initial implementation of `WordPress_Cache`, we were expecting an object of type `WP_Object_Cache` in the constructor, which was not always the case and could result in fatal errors. This new implementation tries to be more agnostic and work correctly in most scenarios.

## Motivation and Context
Fixes #749 

## How Has This Been Tested?
Manual local testing with a few well-known caching plugins. In one case, this patch actually had a beneficial result for object caching (didn't work in 3.2.0 release, but did work with this patch). However, this testing was done on a best-effort basis and some caching plugins didn't completely work due to the nature of the local devenv. If possible, we should test those changes in the environment that surfaced this issue. But this PR seems to be beneficial and had an effect in one case. No fatal errors were encountered during testing with this patch or the original 3.2.0 release.

### CODE REVIEW

File: src/RemoteAPI/class-wordpress-cache.php [hunk 1]
```diff
@@ -62,7 +45,7 @@ public function get( $key, string $group = '', bool $force = false, bool $found
 	 *                           Default 0 (no expiration).
 	 * @return bool True on success, false on failure.
 	 */
-	public function set( $key, $data, string $group = '', int $expire = 0 ): bool {
-		return $this->cache->set( $key, $data, $group, $expire );
+	public function set( $key, $data, string $group = '', $expire = 0 ): bool {
+		return wp_cache_set( $key, $data, $group, $expire ); // phpcs:ignore WordPressVIPMinimum.Performance.LowExpiryCacheTime.CacheTimeUndetermined
```
Comment (pauarge) [inline src/RemoteAPI/class-wordpress-cache.php]:
```suggestion
		// phpcs:ignore WordPressVIPMinimum.Performance.LowExpiryCacheTime.CacheTimeUndetermined
		return wp_cache_set( $key, $data, $group, $expire );
```

**Review by pauarge — APPROVED** [review]
LGTM
